# ----------------------------------------------------------------------
# YAML Configuration: File Paths for Input Parquet Data
#
# This file maps logical dataset names to their corresponding Parquet files
# stored in blob storage. These mappings are used during dynamic loading
# of UDM 
# ----------------------------------------------------------------------

# udm: "Pre-Allocated UDMPre_Allocated_UDM_Final.parquet"             # First Version
# udm: "MathCO_ Allocated_UDM_Preliminary.parquet"                      #Second Version
# udm: "MathCO_ Allocated_UDM_Preliminary_09102025.parquet"                   # Third Version
# udm: "MathCO_ Allocated_UDM_Preliminary_20251017.parquet"                   # Fourth Version
# udm: "MathCO_ Allocated_UDM_Preliminary_20251023.parquet"                   # Fifth Version
udm6: "MathCO_ Allocated_UDM_Preliminary_20251024.parquet"                   # Sixth Version
# udm: "MathCO_ Allocated_UDM_Preliminary_20251027.parquet"                   # Seventh Version
# udm: "MathCO_ Allocated_UDM_Preliminary_20251028.parquet"                   # Eighth Version
# udm: "MathCO_ Allocated_UDM_Preliminary_20251029.parquet"                   # Ninth Version
# udm: "MathCO_ Allocated_UDM_Preliminary_20251101.parquet"                   # Tenth Version
# udm: "MathCO_ Allocated_UDM_Preliminary_20251105.parquet"                   # Eleventh Version
# udm: "MathCO_ Allocated_UDM_Preliminary20251110.parquet"                   # Twelvth Version
udm: "MathCO_ Allocated_UDM_Preliminary_20251113.parquet"                   # Final Version