# ----------------------------------------------------------------------
# YAML Configuration for Benchamrk Data Validation Rules
# 
# This configuration is used by the `Validations` class to apply 
# multiple layers of quality checks on the Benchamrk dataset.
# 
# Structure & Description:
#
# - validation_score_required: Minimum overall Data Quality Score (%) required 
#   for pipeline success. Failing this will stop further execution.
#
# - column_existence: List of required columns that must exist in the dataset.
#
# - primary_key_validation: Combination of columns that must form a unique key.
#   Duplicate rows based on these will be flagged.
#
# - null_threshold_validation: Specifies max allowable null percentage per column.
#   A value of `0` means nulls are not allowed at all.
#
# - datatype_validation: Expected Spark data types per column.
#
# - min_range_validation / max_range_validation: Indicates that the column should 
#   have numeric values within an acceptable range (actual limits may be inferred 
#   from business rules or derived dynamically).
#
# - flag_column_validation: Meant for binary indicators.
#
# - format_validation:  Intended for regex or date patterns.
#
# - business_rule_validation: Placeholder for complex rule checks (e.g. cross-field).
#
# - data_freshness_validation: Placeholder for validating if the dataset is 
#   updated within an acceptable timeframe.
# ----------------------------------------------------------------------
validation_score_required: 50

column_existence:
  - 'cohort'
  - 'cost_format'
  - 'cost_metric' 
  - 'benchmark'
  - 'load_date'
  
primary_key_validation: 
  - 'cohort'
  - 'cost_format'
  - 'cost_metric' 

null_threshold_validation:
  cohort : 0
  cost_format : 0
  cost_metric :  0
  benchmark : 0
  load_date : 0

datatype_validation:
  cohort : STRING
  cost_format : STRING
  cost_metric :  STRING
  benchmark : DOUBLE
  load_date : STRING


min_range_validation: None

max_range_validation: None

flag_column_validation:
  kosher_indicator : ["Kosher","Non-Kosher"]
  organic_indicator : ["Organic","Non-Organic"]
  gmo_indicator : ["Non-GMO","GMO"]
  lactose_indicator : ["Lactose-Free","Contains Lactose"]



format_validation: None
  
business_rule_validation: None

data_freshness_validation: None